### ISSUE TITLE
transfer disqus comments

### ISSUE THREAD

**Issue by njtierney** [rbind/njtierney.com#4]
Not that there are that many to transfer, but work out how to do that properly

**Comment by njtierney** [comment]
I've added the custom footer now, need to check why this isn't working

**Comment by njtierney** [comment]
I've added the footer from [this pull request](https://github.com/yihui/hugo-xmin/pull/4), and added my disqus shortname, not sure what else there is to do here.

**Comment by njtierney** [comment]
@yihui have I missed something with my disqus stuff?

**Comment by yihui** [comment]
Yes, a proper `baseurl`: https://bookdown.org/yihui/blogdown/configuration.html#options

You do not see a full `baseurl` in the hugo-xmin repo only because I hid it behind the scenes on Netlify:

![image](https://user-images.githubusercontent.com/163582/27489673-07c87046-5801-11e7-917a-e65169d9cb05.png)

That said, I think this issue should be fixed in Hugo. I noticed it long time ago but it didn't bother me enough. You are not the first person who has been bitten by this issue, but I have finally submitted a PR to Hugo to fix it: https://github.com/gohugoio/hugo/pull/3639

You can also customize your disqus.html. I have a fairly complicated one for myself and I don't think you want to borrow it: https://github.com/rbind/yihui/blob/master/layouts/partials/disqus.html included at https://github.com/rbind/yihui/blob/master/layouts/_default/single.html#L20

**Comment by njtierney** [comment]
Hey @yihui - I'm not sure what I'm missing on my site but I noticed that someone else seems to ahve the [same/similar problem](https://github.com/rbind/blogsite/issues/1), do you have an idea on what I might be missing?

**Comment by yihui** [comment]
My hugo-xmin does not support Disqus comments by default, but I have shown how: https://github.com/yihui/hugo-xmin/pull/4/files

**Comment by njtierney** [comment]
OK thanks for that! I missed adding in the footer, I've worked through the [disqus troubleshooting guide](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22), but  it looks like I'll need to contact their team, as their suggestions haven't fixed it.

**Comment by yihui** [comment]
No need to contact them. I can spot the problem in 5 seconds. In short, upgrade your Hugo version on Netlify (because of the issues I fixed in https://github.com/gohugoio/hugo/pull/3639). Here is the config info of one of my websites:

![image](https://user-images.githubusercontent.com/163582/28762769-b83b0f8e-757e-11e7-9aef-0bd9b7054f9e.png)

**Comment by njtierney** [comment]
oh wow, thank you so much! It works now! 😄 

I just need to migrate the disqus comments over now, need to do some reading on that.

**Comment by yihui** [comment]
Yes. Migration is not too bad. Basically you just prepare a CSV file containing old and new URLs. Good luck!

**Comment by njtierney** [comment]
Thanks!

**Comment by yihui** [comment]
BTW, enable HTTPS! It is free on Netlify. Why HTTPS? https://https.cio.gov/everything/

**Comment by njtierney** [comment]
Awesome! I think I'm all secure now.

Hmm, any thoughts on how to disable commenting on every single page? Like to get it to run only on posts, or can you specify some "comments = TRUE" argument in the YAML?

**Comment by yihui** [comment]
Take a look at https://github.com/yihui/hugo-lithium-theme/blob/master/layouts/partials/disqus.html#L1

**Comment by njtierney** [comment]
Going to look into using utteranc.es instead of disqus
